apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aniq-api
  namespace: argocd
spec:
  destination:
    namespace: aniq
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/argocd/aniq-runners-list-api
    repoURL: https://github.com/adhasahar97/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SetDeletionFinalizer=true