apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- log-generator.yaml
- httpd.yaml
- aniq-api.yaml

patches:
- path: repo-url-patch.yaml
  target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
